"""Normalize frequency outputs for each prompt.

This script scans the dataset for ``frequency/`` folders generated by
``frequency_counter.py``. For every prompt it loads ``frequencies.json``,
normalises token spellings (case, spacing, punctuation, ordering of compound
values), merges near-duplicate tokens using fuzzy matching, and writes the
cleaned results to ``clean_frequency/`` (JSON and CSV). Totals are preserved.
"""

import argparse
import csv
import json
import logging
import re
from difflib import SequenceMatcher
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Dict, Iterable, List, Optional, Set

logger = logging.getLogger(__name__)

# Categories mirror the output schema from frequency_counter.py
CATEGORIES = [
    "scene_mood",
    "scene_color_temperature",
    "scene_contrast_level",
    "scene_aesthetic_qualities",
    "scene_dominant_colors",
    "scene_weather",
    "scene_ceiling_color",
    "scene_floor_color",
    "scene_wall_color",
    "camera_depth_of_field",
    "camera_framing",
    "camera_perspective",
    "people_gender_presentation",
    "people_skin_tone",
    "people_age_range",
    "people_body_type",
    "people_pose",
    "people_expression",
    "people_activities",
    "people_accessories",
    "people_eyewear_type",
    "people_eyewear_present",
    "people_head_covering_type",
    "people_head_covering_present",
    "people_hair_present",
    "people_hair_color",
    "people_hair_style",
    "people_facial_hair_present",
    "people_facial_hair_style",
    "people_facial_hair_color",
    "people_role_hint",
    "people_clothing_garment",
    "people_clothing_garment_color",
    "objects_items",
    "objects_size",
    "objects_color",
    "objects_material",
    "objects_item_size",
    "objects_item_color",
    "objects_item_material",
    "safety_hazards",
    "safety_nsfw",
]


def _write_atomic(path: Path, data: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as tmp_file:
        tmp_file.write(data)
        tmp_path = Path(tmp_file.name)
    tmp_path.replace(path)


def _write_csv(path: Path, rows: List[List[str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", newline="", dir=path.parent, delete=False) as tmp_file:
        writer = csv.writer(tmp_file)
        writer.writerows(rows)
        tmp_path = Path(tmp_file.name)
    tmp_path.replace(path)



def _normalise_simple(token: str) -> str:
    token = token.strip().lower()
    token = token.replace("_", " ").replace("-", " ")
    token = re.sub(r"[^\w|=, ]+", "", token)
    token = re.sub(r"\s+", " ", token)
    return token.strip()


def _canonicalize(value: str) -> str:
    lowered = value.strip().lower()
    if not lowered:
        return ""

    if "shirt" in lowered:
        return "shirt"
    if "drum" in lowered:
        return "drum"
    if ("mic" in lowered or "microphone" in lowered) and "stand" in lowered:
        return "mic_stand"
    if lowered == "mic" or lowered == "microphone":
        return "microphone"
    if "stage" in lowered and "light" in lowered:
        return "stage_light"
    if "stage" in lowered and "monitor" in lowered:
        return "stage_monitor"
    if lowered.endswith("s") and lowered[:-1] == lowered.rstrip("s"):
        return lowered[:-1]

    return lowered

def _normalise_combo(token: str) -> str:
    parts = token.split("|")
    normalised_parts: List[str] = []
    for part in parts:
        if "=" in part:
            key, value = part.split("=", 1)
            key_norm = _canonicalize(_normalise_simple(key)).replace(" ", "_")
            values = [
                _canonicalize(_normalise_simple(v)).replace(" ", "_")
                for v in value.split(",")
                if _canonicalize(_normalise_simple(v))
            ]
            value_norm = ",".join(sorted(set(values)))
            normalised_parts.append(f"{key_norm}={value_norm}")
        else:
            part_norm = _canonicalize(_normalise_simple(part)).replace(" ", "_")
            if part_norm:
                normalised_parts.append(part_norm)
    return "|".join(normalised_parts)

def _normalise_token(token: str, category: str) -> str:
    base = _normalise_simple(token)
    if not base:
        return ""
    if "|" in token or "=" in token or "," in token:
        return _normalise_combo(token)
    canon = _canonicalize(base)
    return canon.replace(" ", "_")



def _token_to_vector(token: str, dimension: int = 3) -> List[float]:
    result = [0.0] * dimension
    if not token:
        return result
    for idx, ch in enumerate(token):
        result[idx % dimension] += (ord(ch) - 96 if ch.isalpha() else ord(ch) % 32) * 0.1
    # Normalize
    norm = sum(value * value for value in result) ** 0.5
    if norm > 0:
        result = [value / norm for value in result]
    return result


def _cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
    if not vec_a or not vec_b or len(vec_a) != len(vec_b):
        return 0.0
    dot = sum(a * b for a, b in zip(vec_a, vec_b))
    if not -1.0 <= dot <= 1.0:
        dot = max(min(dot, 1.0), -1.0)
    return dot


def _merge_similar(tokens: Dict[str, int], threshold: float = 0.99) -> Dict[str, int]:
    if not tokens:
        return {}

    vectors: Dict[str, List[float]] = {token: _token_to_vector(token) for token in tokens}
    merged: Dict[str, int] = {}
    canonical: List[str] = []

    for token, count in tokens.items():
        matched: Optional[str] = None
        for canon in canonical:
            similarity = _cosine_similarity(vectors[token], vectors[canon])
            if similarity >= threshold:
                merged[canon] += count
                matched = canon
                break
        if matched is None:
            merged[token] = count
            canonical.append(token)

    return merged

def _load_frequency_json(path: Path) -> Optional[Dict[str, Any]]:
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to read %s: %s", path, exc)
        return None
    if not isinstance(data, dict):
        return None
    return data


def _clean_category(tokens: Dict[str, int], category: str) -> Dict[str, int]:
    cleaned: Dict[str, int] = {}
    for token, count in tokens.items():
        if not isinstance(token, str):
            token = str(token)
        norm = _normalise_token(token, category)
        if not norm:
            continue
        cleaned[norm] = cleaned.get(norm, 0) + int(count)
    return _merge_similar(cleaned)


def _clean_frequencies(data: Dict[str, Any]) -> Dict[str, Any]:
    cleaned: Dict[str, Any] = {"totals": data.get("totals", {})}
    for category, counts in data.items():
        if category == "totals":
            continue
        if not isinstance(counts, dict):
            continue
        cleaned[category] = _clean_category(counts, category)
    return cleaned


def _process_prompt_frequency(freq_dir: Path) -> Optional[Path]:
    freq_json = freq_dir / "frequencies.json"
    if not freq_json.exists():
        return None

    data = _load_frequency_json(freq_json)
    if data is None:
        return None

    cleaned = _clean_frequencies(data)
    clean_dir = freq_dir.parent / "clean_frequency"
    clean_dir.mkdir(parents=True, exist_ok=True)

    _write_atomic(clean_dir / "frequencies.json", json.dumps(cleaned, indent=2, sort_keys=True))

    rows: List[List[str]] = [["category", "token", "count"]]
    for category in CATEGORIES:
        counts = cleaned.get(category, {})
        if not isinstance(counts, dict):
            continue
        for token, count in sorted(counts.items()):
            rows.append([category, token, str(count)])

    totals = cleaned.get("totals", {})
    for key, value in totals.items():
        rows.append(["totals", key, str(value)])

    _write_csv(clean_dir / "frequencies.csv", rows)
    return clean_dir


def _iter_frequency_dirs(dataset_root: Path) -> List[Path]:
    dataset_root = dataset_root.resolve()
    freq_dirs = [p for p in dataset_root.rglob("frequency") if p.is_dir()]
    return sorted(freq_dirs)


def main(argv: Optional[Iterable[str]] = None) -> None:
    parser = argparse.ArgumentParser(
        description="Clean and normalise frequency outputs for each prompt."
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=Path("./dataset"),
        help="Path to the dataset root (default: ./dataset)",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"],
        help="Logging verbosity (default: INFO)",
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=getattr(logging, args.log_level))

    dataset_root = args.dataset.resolve()
    freq_dirs = _iter_frequency_dirs(dataset_root)
    if not freq_dirs:
        print(f"No frequency directories found under {dataset_root}. Nothing to clean.")
        return

    processed_prompts = 0
    for freq_dir in freq_dirs:
        result = _process_prompt_frequency(freq_dir)
        if result is not None:
            processed_prompts += 1
            logger.info("Cleaned frequencies for %s", freq_dir.parent)

    print(
        f"Cleaned frequency outputs for {processed_prompts} prompt(s). "
        f"Normalised files are stored in each prompt's clean_frequency/ directory."
    )


if __name__ == "__main__":
    main()
