"""Normalize frequency outputs for each prompt.

This script scans the dataset for ``frequency/`` folders generated by
``frequency_counter.py``. For every prompt it loads ``frequencies.json``,
normalises token spellings (case, spacing, punctuation, ordering of compound
values), merges near-duplicate tokens using sentence-embedding similarity, and
writes the cleaned results to ``clean_frequency/`` (JSON and CSV). Totals are
preserved.
"""

import argparse
import json
import logging
import re
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any, Dict, Iterable, List, NamedTuple, Optional, Set, Tuple

from .io_utils import write_atomic_csv, write_atomic_text

import numpy as np

logger = logging.getLogger(__name__)

STRUCTURAL_MARKERS = {"|", "=", ","}
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_SIMILARITY_THRESHOLD = 0.8

# Categories mirror the output schema from frequency_counter.py
CATEGORIES = [
    "scene_mood",
    "scene_color_temperature",
    "scene_contrast_level",
    "scene_aesthetic_qualities",
    "scene_dominant_colors",
    "scene_weather",
    "scene_ceiling_color",
    "scene_floor_color",
    "scene_wall_color",
    "camera_depth_of_field",
    "camera_framing",
    "camera_perspective",
    "people_gender_presentation",
    "people_skin_tone",
    "people_age_range",
    "people_body_type",
    "people_pose",
    "people_expression",
    "people_activities",
    "people_accessories",
    "people_eyewear_type",
    "people_eyewear_present",
    "people_head_covering_type",
    "people_head_covering_present",
    "people_hair_present",
    "people_hair_color",
    "people_hair_style",
    "people_facial_hair_present",
    "people_facial_hair_style",
    "people_facial_hair_color",
    "people_role_hint",
    "people_clothing_garment",
    "people_clothing_garment_color",
    "objects_items",
    "objects_size",
    "objects_color",
    "objects_material",
    "objects_item_size",
    "objects_item_color",
    "objects_item_material",
    "safety_hazards",
    "safety_nsfw",
]


def _normalise_simple(token: str) -> str:
    token = token.strip().lower()
    token = token.replace("_", " ").replace("-", " ")
    token = re.sub(r"[^\w|=, ]+", "", token)
    token = re.sub(r"\s+", " ", token)
    return token.strip()


def _is_structured_token(token: str) -> bool:
    return any(marker in token for marker in STRUCTURAL_MARKERS)


def _token_quality(token: str, count: int = 0) -> Tuple[int, int, int, int, str]:
    words = len(token.split())
    digits = sum(ch.isdigit() for ch in token)
    underscores = token.count("_")
    return (words, digits, underscores, -count, len(token), token)


def _normalize_key(token: str) -> str:
    return _normalise_simple(token).replace(" ", "_")


def _string_similarity_gate(lhs: str, rhs: str) -> bool:
    ratio = SequenceMatcher(None, lhs, rhs).ratio()
    if ratio >= 0.65:
        return True
    lhs_words = set(lhs.split())
    rhs_words = set(rhs.split())
    if lhs_words and rhs_words and lhs_words.intersection(rhs_words):
        return True
    lhs_compact = lhs.replace(" ", "")
    rhs_compact = rhs.replace(" ", "")
    return lhs_compact.startswith(rhs_compact) or rhs_compact.startswith(lhs_compact)


_EMBEDDING_MODEL = None
_EMBEDDING_CACHE: Dict[str, np.ndarray] = {}


def _ensure_embedding_model():
    global _EMBEDDING_MODEL
    if _EMBEDDING_MODEL is None:
        try:
            from sentence_transformers import SentenceTransformer
        except ImportError as exc:  # pragma: no cover - import dependency
            raise RuntimeError(
                "sentence-transformers package is required for semantic token normalisation. "
                "Install it with `pip install sentence-transformers`."
            ) from exc
        _EMBEDDING_MODEL = SentenceTransformer(EMBEDDING_MODEL_NAME)
    return _EMBEDDING_MODEL


def _embed(token: str) -> np.ndarray:
    if token in _EMBEDDING_CACHE:
        return _EMBEDDING_CACHE[token]
    model = _ensure_embedding_model()
    vector = model.encode([token], normalize_embeddings=True)[0]
    _EMBEDDING_CACHE[token] = vector
    return vector


def _cosine_similarity(vec_a: np.ndarray, vec_b: np.ndarray) -> float:
    return float(np.dot(vec_a, vec_b))


@dataclass
class SemanticCluster:
    label: str
    embedding: np.ndarray
    best_label: str
    best_quality: Tuple[int, int, int, int, str]
    total_weight: float = 0.0
    members: Set[str] = field(default_factory=set)

    def add_member(self, token: str, vector: np.ndarray, weight: float, quality: Tuple[int, int, int, int, str]) -> bool:
        if weight <= 0:
            weight = 1.0
        current_weight = self.total_weight or 1.0
        combined = self.embedding * current_weight + vector * weight
        norm = np.linalg.norm(combined)
        if norm:
            self.embedding = combined / norm
        else:
            self.embedding = combined
        self.total_weight = current_weight + weight
        self.members.add(token)
        if quality < self.best_quality:
            self.best_label = token
            self.best_quality = quality
            return True
        return False


class SemanticNormalizer:
    def __init__(self, similarity_threshold: float = EMBEDDING_SIMILARITY_THRESHOLD):
        self.similarity_threshold = similarity_threshold
        self._clusters: List[SemanticCluster] = []
        self._cache: Dict[str, str] = {}

    def _canonical_simple(self, token: str, count: int = 0) -> str:
        if not token:
            return ""
        if token in self._cache:
            return self._cache[token]

        vector = _embed(token)
        quality = _token_quality(token.replace(" ", "_"), count)

        best_cluster: Optional[SemanticCluster] = None
        best_score = 0.0
        for cluster in self._clusters:
            score = _cosine_similarity(vector, cluster.embedding)
            if score >= self.similarity_threshold and score > best_score:
                if _string_similarity_gate(token, cluster.best_label):
                    best_cluster = cluster
                    best_score = score

        if best_cluster is None:
            cluster = SemanticCluster(
                label=token,
                embedding=vector,
                best_label=token,
                best_quality=quality,
                total_weight=max(count, 1),
            )
            cluster.members.add(token)
            self._clusters.append(cluster)
            canonical_label = token
        else:
            updated = best_cluster.add_member(token, vector, max(count, 1), quality)
            canonical_label = best_cluster.best_label
            if updated:
                canonical_value = canonical_label.replace(" ", "_")
                for member in best_cluster.members:
                    self._cache[member] = canonical_value

        canonical = canonical_label.replace(" ", "_")
        self._cache[token] = canonical
        return canonical

    def _normalise_structured(self, token: str, count: int) -> str:
        parts = token.split("|")
        normalised_parts: List[str] = []
        for part in parts:
            if "=" in part:
                key, value = part.split("=", 1)
                key_norm = _normalize_key(key)
                values: List[str] = []
                for raw in value.split(","):
                    value_norm = self._canonical_simple(_normalise_simple(raw), count)
                    if value_norm:
                        values.append(value_norm)
                if not key_norm:
                    continue
                if values:
                    normalised_parts.append(f"{key_norm}=" + ",".join(sorted(set(values))))
                else:
                    normalised_parts.append(key_norm)
            else:
                part_norm = self._canonical_simple(_normalise_simple(part), count)
                if part_norm:
                    normalised_parts.append(part_norm)
        return "|".join(normalised_parts)

    def normalise(self, token: str, count: int = 0) -> str:
        if not isinstance(token, str):
            token = str(token)
        base = _normalise_simple(token)
        if not base:
            return ""
        if _is_structured_token(token):
            return self._normalise_structured(token, count)
        return self._canonical_simple(base, count)


def _load_frequency_json(path: Path) -> Optional[Dict[str, Any]]:
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to read %s: %s", path, exc)
        return None
    if not isinstance(data, dict):
        return None
    return data


def _clean_category(tokens: Dict[str, int], category: str) -> Dict[str, int]:
    normalizer = SemanticNormalizer()
    observed: List[Tuple[str, int]] = []
    for token, count in tokens.items():
        if isinstance(count, (int, float)):
            weight = int(round(count))
        else:
            weight = 1
        if weight <= 0:
            weight = 1
        token_str = token if isinstance(token, str) else str(token)
        normalizer.normalise(token_str, weight)
        observed.append((token_str, weight))

    cleaned: Dict[str, int] = {}
    for token_str, weight in observed:
        norm = normalizer.normalise(token_str, weight)
        if not norm:
            continue
        cleaned[norm] = cleaned.get(norm, 0) + weight
    return cleaned


def _clean_frequencies(data: Dict[str, Any]) -> Dict[str, Any]:
    cleaned: Dict[str, Any] = {"totals": data.get("totals", {})}
    for category, counts in data.items():
        if category == "totals":
            continue
        if not isinstance(counts, dict):
            continue
        cleaned[category] = _clean_category(counts, category)
    return cleaned


def _process_prompt_frequency(freq_dir: Path) -> Optional[Path]:
    freq_json = freq_dir / "frequencies.json"
    if not freq_json.exists():
        return None

    data = _load_frequency_json(freq_json)
    if data is None:
        return None

    cleaned = _clean_frequencies(data)
    clean_dir = freq_dir.parent / "clean_frequency"
    clean_dir.mkdir(parents=True, exist_ok=True)

    write_atomic_text(clean_dir / "frequencies.json", json.dumps(cleaned, indent=2, sort_keys=True))

    rows: List[List[str]] = [["category", "token", "count"]]
    for category in CATEGORIES:
        counts = cleaned.get(category, {})
        if not isinstance(counts, dict):
            continue
        for token, count in sorted(counts.items()):
            rows.append([category, token, str(count)])

    totals = cleaned.get("totals", {})
    for key, value in totals.items():
        rows.append(["totals", key, str(value)])

    write_atomic_csv(clean_dir / "frequencies.csv", rows)
    return clean_dir


def _iter_frequency_dirs(dataset_root: Path) -> List[Path]:
    dataset_root = dataset_root.resolve()
    freq_dirs = [p for p in dataset_root.rglob("frequency") if p.is_dir()]
    return sorted(freq_dirs)


class FrequencyCleanResult(NamedTuple):
    prompts_visited: int
    prompts_cleaned: int


def clean_dataset(dataset_root: Path) -> FrequencyCleanResult:
    dataset_root = dataset_root.resolve()
    freq_dirs = _iter_frequency_dirs(dataset_root)
    if not freq_dirs:
        logger.info("No frequency directories found under %s. Nothing to clean.", dataset_root)
        return FrequencyCleanResult(0, 0)

    cleaned = 0
    for freq_dir in freq_dirs:
        result = _process_prompt_frequency(freq_dir)
        if result is not None:
            cleaned += 1
            logger.info("Cleaned frequencies for %s", freq_dir.parent)

    return FrequencyCleanResult(len(freq_dirs), cleaned)


def main(argv: Optional[Iterable[str]] = None) -> None:
    parser = argparse.ArgumentParser(
        description="Clean and normalise frequency outputs for each prompt."
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=Path("./dataset"),
        help="Path to the dataset root (default: ./dataset)",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"],
        help="Logging verbosity (default: INFO)",
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=getattr(logging, args.log_level))

    result = clean_dataset(args.dataset)
    dataset_root = args.dataset.resolve()
    if result.prompts_visited == 0:
        print(f"No frequency directories found under {dataset_root}. Nothing to clean.")
        return

    print(
        f"Cleaned frequency outputs for {result.prompts_cleaned} prompt(s). "
        f"Processed {result.prompts_visited} frequency folder(s) in total. "
        f"Normalised files are stored in each prompt's clean_frequency/ directory."
    )


if __name__ == "__main__":
    main()
